create extension if not exists pgtap with schema extensions;
begin;
set local search_path = public, extensions;
select plan(46);
select has_table('public','account_principals','account type registry exists');
select has_table('public','staff_members','staff registry exists');
select ok(to_regclass('public.organizations') is null,'organizations removed');
select ok(to_regclass('public.organization_members') is null,'organization memberships removed');
select ok(to_regclass('public.reservation_payments') is null,'reservation payments removed');
select ok(to_regclass('public.staff_quotes') is null,'staff quotations removed');
select has_table('public','customer_billing_profiles','personal GST billing profile exists');
select has_table('public','checkout_sessions','checkout exists');
select has_table('public','payment_attempts','durable payments exist');
select has_table('public','order_files','private file registry exists');
select has_function('public','ensure_customer_account',array['text','text'],'customer account creation is database authoritative');
select has_function('public','staff_transition_order',array['uuid','order_status','text','text','text'],'staff status transition RPC exists');
select has_function('public','review_artwork_file',array['uuid','artwork_review_status','text'],'artwork review RPC exists');
select has_function('public','finalize_checkout_full_payment',array['uuid','text','bigint','jsonb','jsonb'],'atomic full payment finalizer exists');
select has_function('public','customer_payment_summaries',array['uuid'],'customer-safe payment summary exists');
select has_function('public','staff_payment_summaries',array['uuid'],'staff-safe payment summary exists');
select has_function('public','decide_order_cancellation',array['uuid','boolean','text'],'Founder cancellation decision exists');
select has_function('public','record_order_refund',array['uuid','boolean','text','text'],'Founder refund evidence RPC exists');
select ok(to_regprocedure('public.reopen_order_configuration(uuid,text)') is null,'Founder configuration reopen RPC removed');
select ok(to_regprocedure('public.update_order_configuration(uuid,jsonb,text)') is null,'paid-order configuration RPC removed');
select ok(to_regprocedure('public.update_order_configuration_validated(uuid,jsonb,text)') is null,'validated configuration RPC removed');
select ok(to_regprocedure('public.finalize_staff_quote_offline_payment(uuid,text,uuid,jsonb)') is null,'offline payment finalizer removed');
select is((select array_agg(e.enumlabel order by e.enumsortorder)::text from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='staff_role'),'{'||'founder,operations'||'}','only Founder and Operations roles exist');
select ok((select relrowsecurity from pg_class where oid='public.orders'::regclass),'orders RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.order_files'::regclass),'files RLS enabled');
select ok(not has_table_privilege('authenticated','public.payment_attempts','SELECT'),'raw payment table is not directly readable');
select ok(exists(select 1 from pg_constraint where conrelid='public.order_files'::regclass and pg_get_constraintdef(oid) ilike '%num_nonnulls(order_id, design_project_id) = 1%'),'files have exactly one owner target');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name ilike '%organization%'),'orders have no organization ownership');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='checkout_sessions' and column_name ilike '%reservation%'),'checkout has no reservation fields');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='cancellation_requests_one_pending_idx'),'one pending cancellation per order');
select has_table('public','order_artwork_requirements','artwork revision ledger exists');
select has_table('public','legal_document_versions','legal versions are server controlled');
select has_column('public','order_files','object_cleanup_completed_at','expired object cleanup is tracked');
select has_column('public','order_configuration_revisions','previous_order_status','configuration audit preserves prior status');
select has_column('public','order_configuration_revisions','production_revision','production revisions are explicit');
select has_function('public','customer_artwork_requirements',array['uuid'],'customer-safe active artwork RPC exists');
select has_function('public','expire_private_upload_slots',array[]::text[],'lazy upload expiration exists');
select has_function('public','claim_expired_private_uploads',array['integer'],'scheduled upload cleanup claim exists');
select has_function('public','update_my_profile',array['text','text','text','text','text','text','text'],'controlled profile update exists');
select has_function('public','accept_legal_terms',array['text','text'],'controlled legal acceptance exists');
select ok(not has_table_privilege('authenticated','public.profiles','UPDATE'),'customers cannot directly update profile audit fields');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='order_artwork_requirement_one_active_uidx'),'one active artwork revision is database enforced');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='order_artwork_requirement_revision_uidx'),'artwork revision numbers are unique per requirement');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='order_files_expired_cleanup_idx'),'expired upload cleanup is indexed');
select ok(not exists(select 1 from information_schema.routine_privileges where routine_schema='public' and routine_name='claim_expired_private_uploads' and grantee='authenticated'),'customers cannot claim private object cleanup work');
select ok(not has_function_privilege('authenticated','public.capture_order_artwork_requirement()','EXECUTE'),'trigger-only artwork capture has no browser execution grant');
select * from finish();
rollback;
