create extension if not exists pgtap with schema extensions;
begin;
set local search_path = public, extensions;
select plan(28);
select has_table('public','account_principals','account type registry exists');
select has_table('public','staff_members','staff registry exists');
select ok(to_regclass('public.organizations') is null,'organizations removed');
select ok(to_regclass('public.organization_members') is null,'organization memberships removed');
select ok(to_regclass('public.reservation_payments') is null,'reservation payments removed');
select has_table('public','staff_quotes','staff quotations exist');
select has_table('public','customer_billing_profiles','personal GST billing profile exists');
select has_table('public','custom_checkout_sessions','durable checkout exists');
select has_table('public','payment_attempts','durable payments exist');
select has_table('public','order_files','private file registry exists');
select has_function('public','ensure_customer_account',array['text','text'],'customer account creation is database authoritative');
select has_function('public','staff_transition_order',array['uuid','order_status','text','text','text'],'staff status transition RPC exists');
select has_function('public','review_artwork_file',array['uuid','artwork_review_status','text'],'artwork review RPC exists');
select has_function('public','finalize_custom_checkout_full_payment',array['uuid','text','bigint','jsonb','jsonb'],'atomic full payment finalizer exists');
select has_function('public','customer_payment_summaries',array['uuid'],'customer-safe payment summary exists');
select has_function('public','staff_payment_summaries',array['uuid'],'staff-safe payment summary exists');
select has_function('public','decide_order_cancellation',array['uuid','boolean','text'],'Founder cancellation decision exists');
select has_function('public','record_order_refund',array['uuid','boolean','text','text'],'Founder refund evidence RPC exists');
select has_function('public','reopen_order_configuration',array['uuid','text'],'Founder controlled reopen exists');
select has_function('public','finalize_staff_quote_offline_payment',array['uuid','text','uuid','jsonb'],'Founder offline-payment finalizer exists');
select is((select array_agg(e.enumlabel order by e.enumsortorder)::text from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='staff_role'),'{'||'founder,operations'||'}','only Founder and Operations roles exist');
select ok((select relrowsecurity from pg_class where oid='public.orders'::regclass),'orders RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.order_files'::regclass),'files RLS enabled');
select ok(not has_table_privilege('authenticated','public.payment_attempts','SELECT'),'raw payment table is not directly readable');
select ok(exists(select 1 from pg_constraint where conrelid='public.order_files'::regclass and pg_get_constraintdef(oid) ilike '%num_nonnulls(order_id, design_project_id, staff_quote_id) = 1%'),'files have exactly one owner target');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name ilike '%organization%'),'orders have no organization ownership');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='custom_checkout_sessions' and column_name ilike '%reservation%'),'checkout has no reservation fields');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='cancellation_requests_one_pending_idx'),'one pending cancellation per order');
select * from finish();
rollback;
