import type { StaffRole } from "@/lib/auth/constants";

export const STAFF_PERMISSIONS = [
  "view_profiles",
  "view_organizations",
  "view_all_orders",
  "view_internal_notes",
  "add_internal_note",
  "send_customer_update",
  "manage_action_requests",
  "assign_order",
  "set_order_priority",
  "set_expected_dates",
  "change_order_status",
  "change_high_impact_status",
  "change_file_visibility",
  "edit_commercial",
  "change_production_status",
  "upload_artwork_proof",
  "view_payment_payload",
  "retry_invoice_job",
  "refund_workflow",
  "upload_qc_evidence",
  "manage_approvals",
  "manage_shipments",
  "view_audit",
  "view_jobs",
  "manage_staff",
] as const;

export type StaffPermission = (typeof STAFF_PERMISSIONS)[number];

const ALL_NON_READ_ONLY: StaffRole[] = [
  "super_admin",
  "operations_admin",
  "sales",
  "production",
  "artwork",
  "finance",
  "qc",
  "dispatch",
  "support",
];

export const STAFF_PERMISSION_MATRIX: Record<StaffPermission, StaffRole[]> = {
  view_profiles: [
    "super_admin", "operations_admin", "sales", "production", "artwork",
    "finance", "qc", "dispatch", "support", "read_only",
  ],
  view_organizations: [
    "super_admin", "operations_admin", "sales", "production", "artwork",
    "finance", "qc", "dispatch", "support", "read_only",
  ],
  view_all_orders: [
    "super_admin",
    "operations_admin",
    "sales",
    "production",
    "artwork",
    "finance",
    "qc",
    "dispatch",
    "support",
    "read_only",
  ],
  view_internal_notes: [
    "super_admin",
    "operations_admin",
    "sales",
    "production",
    "artwork",
    "finance",
    "qc",
    "dispatch",
    "support",
    "read_only",
  ],
  add_internal_note: ALL_NON_READ_ONLY,
  send_customer_update: ALL_NON_READ_ONLY,
  manage_action_requests: ALL_NON_READ_ONLY,
  assign_order: ["super_admin", "operations_admin", "sales"],
  set_order_priority: ["super_admin", "operations_admin", "sales"],
  set_expected_dates: [
    "super_admin",
    "operations_admin",
    "production",
    "artwork",
    "qc",
    "dispatch",
  ],
  change_order_status: [
    "super_admin",
    "operations_admin",
    "sales",
    "production",
    "artwork",
    "qc",
    "dispatch",
  ],
  change_high_impact_status: ["super_admin", "operations_admin"],
  change_file_visibility: [
    "super_admin",
    "operations_admin",
    "artwork",
    "finance",
    "qc",
    "dispatch",
  ],
  edit_commercial: ["super_admin", "operations_admin", "sales", "finance"],
  change_production_status: [
    "super_admin", "operations_admin", "production", "artwork", "qc", "dispatch",
  ],
  upload_artwork_proof: ["super_admin", "operations_admin", "artwork"],
  view_payment_payload: ["super_admin", "operations_admin", "finance"],
  retry_invoice_job: ["super_admin", "finance"],
  refund_workflow: ["super_admin", "finance"],
  upload_qc_evidence: ["super_admin", "operations_admin", "production", "qc"],
  manage_approvals: ["super_admin", "operations_admin", "artwork"],
  manage_shipments: ["super_admin", "operations_admin", "dispatch"],
  view_audit: ["super_admin", "operations_admin"],
  view_jobs: ["super_admin", "operations_admin", "finance"],
  manage_staff: ["super_admin"],
};

export function roleCan(role: StaffRole, permission: StaffPermission) {
  return STAFF_PERMISSION_MATRIX[permission].includes(role);
}
