import PrivateFileDownloadButton from "@/components/staff/PrivateFileDownloadButton";
import ArtworkReviewForm from "@/components/staff/ArtworkReviewForm";
import TechpackPageHeader from "@/components/portal/TechpackPageHeader";
import { requireStaffPermission } from "@/lib/auth/guards";
import type { Tables } from "@/types/database.generated";
type ArtworkRow = Pick<Tables<"order_files">, "id" | "order_id" | "design_project_id" | "original_filename" | "safe_filename" | "content_type" | "byte_size" | "review_status" | "review_reason" | "created_at"> & { orders: { order_number: string } | Array<{ order_number: string }> | null };
type RequirementRow = { revision: number; requirement_key: string; order_files: ArtworkRow | ArtworkRow[] | null };

export default async function ArtworkReviewQueue() {
  const { supabase } = await requireStaffPermission("review_artwork");
  const result = await supabase.from("order_artwork_requirements").select("revision, requirement_key, order_files!inner(id, order_id, design_project_id, original_filename, safe_filename, content_type, byte_size, review_status, review_reason, created_at, kind, upload_status, deleted_at, orders(order_number, customer_snapshot))").eq("is_active", true).eq("order_files.kind", "customer_artwork").eq("order_files.upload_status", "finalized").is("order_files.deleted_at", null).in("order_files.review_status", ["pending_review", "changes_requested"]).order("captured_at", { ascending: true }).limit(200);
  const requirements = (result.data ?? []) as unknown as RequirementRow[];
  return <div className="space-y-5"><TechpackPageHeader eyebrow="Foundry" reference="Artwork control" title="Artwork review" description="Only the current active revision for each paid order line and placement appears here. Superseded files remain in audit history." actions={<span className="techpack-stamp" data-tone="accent">{requirements.length} pending</span>} />{result.error ? <div className="techpack-notice p-5" data-tone="error">{result.error.message}</div> : <div className="grid gap-4">{requirements.length ? requirements.map((requirement) => { const file = Array.isArray(requirement.order_files) ? requirement.order_files[0] : requirement.order_files; if (!file) return null; const order = Array.isArray(file.orders) ? file.orders[0] : file.orders; return <article key={`${requirement.requirement_key}:${requirement.revision}`} className="techpack-surface rounded border p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">{file.safe_filename || file.original_filename}</p><p className="mt-1 text-xs text-black/45">{order?.order_number ?? "Saved design"} · revision {requirement.revision} · {requirement.requirement_key.split(":").at(-1)?.replaceAll("_", " ")} · {file.content_type} · {(file.byte_size / 1024 / 1024).toFixed(1)} MB</p>{file.review_reason ? <p className="mt-2 text-xs text-amber-700">Previous request: {file.review_reason}</p> : null}</div><PrivateFileDownloadButton fileId={file.id} label="Inspect file" /></div><div className="mt-4 border-t border-black/10 pt-4"><ArtworkReviewForm fileId={file.id} /></div></article>; }) : <div className="techpack-surface rounded border p-12 text-center text-sm text-black/45">No active artwork revision is awaiting review.</div>}</div>}</div>;
}
