import Link from "next/link";
import { ArrowRight, CalendarDays } from "lucide-react";
import { requireStaffPermission } from "@/lib/auth/guards";
import { formatOrderCode, formatOrderTimestamp } from "@/lib/orders/format";
import { ORDER_STATUS_LABELS } from "@/lib/staff/statuses";

export default async function StaffOrderQueue() {
  const { supabase } = await requireStaffPermission("view_all_orders");
  const { data: orders, error } = await supabase.from("orders").select("id, order_number, status, public_status, order_type, submitted_at, updated_at, organizations(display_name), order_items(quantity)").order("updated_at", { ascending: false }).limit(200);
  if (error) return <div className="rounded-[4px] border border-dashed p-10 text-center"><h1 className="text-xl font-semibold">Order queue unavailable</h1><p className="mt-2 text-sm text-black/50">The order queue could not be loaded.</p></div>;
  return <div className="space-y-5"><div><p className="text-xs uppercase tracking-[0.18em] text-[#1D49B4]">Staff</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Order queue</h1><p className="mt-2 text-sm text-black/50">Open an order to review its details or change its status.</p></div><section className="techpack-surface overflow-hidden rounded-[4px] border"><div className="flex items-center justify-between border-b border-black/8 px-5 py-4"><h2 className="font-semibold">{(orders ?? []).length.toLocaleString("en-IN")} orders</h2></div><div className="divide-y divide-black/7">{orders?.length ? orders.map((order) => { const organization = Array.isArray(order.organizations) ? order.organizations[0] : order.organizations; const quantity = (order.order_items ?? []).reduce((total, item) => total + item.quantity, 0); return <Link key={order.id} href={`/staff/orders/${order.order_number}`} className="grid gap-3 px-5 py-5 transition hover:bg-white sm:grid-cols-[1.1fr_1fr_0.55fr_auto] sm:items-center"><div><p className="font-semibold">{formatOrderCode(order.order_number)}</p><p className="mt-1 text-xs text-black/45">{organization?.display_name ?? "Customer"}</p></div><div><p className="text-sm font-medium">{ORDER_STATUS_LABELS[order.status]}</p><p className="mt-1 text-xs capitalize text-black/40">{order.order_type.replaceAll("_", " ")}</p></div><p className="text-xs text-black/50">{quantity.toLocaleString("en-IN")} units</p><div className="flex items-center gap-3 text-xs text-black/40"><CalendarDays size={13} />{formatOrderTimestamp(order.updated_at)}<ArrowRight size={16} className="text-[#1D49B4]" /></div></Link>; }) : <p className="px-5 py-16 text-center text-sm text-black/40">No orders yet.</p>}</div></section></div>;
}
