import Link from "next/link";
import { ArrowRight, CalendarDays, ClipboardList } from "lucide-react";
import TechpackPageHeader from "@/components/portal/TechpackPageHeader";
import { requireStaffPermission } from "@/lib/auth/guards";
import { medusaRequest } from "@/lib/medusa/client";
import { formatOrderCode, formatOrderTimestamp, publicOrderStatusLabel } from "@/lib/orders/format";

export default async function StaffOrderQueue({ searchParams = {} }: { searchParams?: { search?: string; offset?: string } }) {
  await requireStaffPermission("view_all_orders");
  let rows: Array<Record<string, unknown>> = [];
  const search = searchParams.search?.trim() ?? "";
  const offset = Number.isInteger(Number(searchParams.offset)) ? Math.max(0, Number(searchParams.offset)) : 0;
  let hasMore = false;
  try { const result = await medusaRequest<{ orders: Array<Record<string, unknown>>; hasMore?: boolean; count?: number }>(`/foundry/orders?limit=25&offset=${offset}${search ? `&search=${encodeURIComponent(search)}` : ""}`, { actor: "staff" }); rows = result.orders ?? []; hasMore = Boolean(result.hasMore); } catch { return <div className="techpack-notice p-6" data-tone="error"><h1 className="text-xl font-semibold">Order queue unavailable</h1><p className="mt-2 text-sm text-black/50">The Medusa operations service could not be reached.</p></div>; }
  const pageUrl = (nextOffset: number) => `/orders?offset=${nextOffset}${search ? `&search=${encodeURIComponent(search)}` : ""}`;
  return <div className="space-y-5"><TechpackPageHeader eyebrow="Foundry" reference="Live order register" title="Order queue" description="Review paid orders and advance production through the backend-enforced workflow." actions={<span className="techpack-stamp" data-tone="accent">{rows.length} records</span>}/><form method="get" className="flex gap-2"><input name="search" defaultValue={search} placeholder="Search order number" className="techpack-control min-w-0 flex-1 rounded border px-3 py-2 text-sm"/><button className="techpack-button" type="submit">Search</button></form><section className="techpack-surface overflow-hidden rounded-sm border"><div className="divide-y divide-(--color-rule)">{rows.length ? rows.map((job) => { const id = String(job.id); const number = String(job.order_number ?? job.order_id); return <Link key={id} href={`/orders/${id}`} className="group grid gap-3 px-5 py-5 transition-colors hover:bg-(--color-cream-soft) sm:grid-cols-[1.5fr_1fr_1fr_auto] sm:items-center"><div><p className="font-semibold">{formatOrderCode(number)}</p><p className="mt-1 text-xs text-black/45">{String(job.order_type ?? "configured")} order</p></div><span className="techpack-stamp" data-tone="accent">{publicOrderStatusLabel(String(job.status ?? "pending"))}</span><div className="flex items-center gap-2 text-xs text-black/40"><CalendarDays size={13}/>{job.updated_at ? formatOrderTimestamp(String(job.updated_at)) : "Recently updated"}</div><ArrowRight size={16} className="text-(--color-accent)"/></Link>; }) : <div className="px-5 py-16 text-center"><ClipboardList className="mx-auto text-(--color-accent)" size={28}/><p className="mt-4 text-sm font-semibold">No matching paid orders</p></div>}</div><div className="flex items-center justify-between border-t p-4 text-sm"><span>Showing {offset + 1}–{offset + rows.length}</span><span className="flex gap-2">{offset > 0 ? <Link className="techpack-button" href={pageUrl(Math.max(0, offset - 25))}>Previous</Link> : null}{hasMore ? <Link className="techpack-button" href={pageUrl(offset + 25)}>Next</Link> : null}</span></div></section></div>;
}
