import { createPrivacyRequest, updateRecoveryPreference } from "@/app/account/privacy-actions";
import AnalyticsPreferencesTrigger from "@/components/privacy/AnalyticsPreferencesTrigger";
import { requireCustomer } from "@/lib/auth/guards";

export default async function AccountPrivacyPage() {
  const { user, supabase } = await requireCustomer("/account/privacy");
  const [{ data: requests }, { data: preference }] = await Promise.all([
    supabase.from("privacy_requests").select("id,request_type,status,created_at").eq("customer_user_id", user.id).order("created_at", { ascending: false }),
    supabase.from("customer_privacy_preferences").select("analytics_enabled,recovery_messages_enabled").eq("customer_user_id", user.id).maybeSingle(),
  ]);
  return <div className="space-y-6"><header><h1 className="text-3xl font-semibold">Privacy controls</h1><p className="mt-2 text-sm text-black/55">Manage optional analytics below, or submit a durable data request.</p></header><form action={updateRecoveryPreference} className="techpack-surface space-y-4 rounded border p-5"><h2 className="font-semibold">Communication preferences</h2><p className="text-sm text-black/55">Account analytics: {preference?.analytics_enabled ? "accepted" : "off"}. Change the analytics choice on this device and in your account.</p><AnalyticsPreferencesTrigger className="text-sm font-semibold text-[var(--color-accent)] hover:underline" /><label className="flex gap-3 text-sm"><input type="checkbox" name="recoveryMessages" defaultChecked={preference?.recovery_messages_enabled === true}/><span><strong>Saved-design reminders</strong><br/><span className="text-black/50">Allow an occasional reminder when an unfinished saved design has been inactive. Transactional order emails are unaffected.</span></span></label><button className="techpack-button">Save communication preference</button></form><form action={createPrivacyRequest} className="techpack-surface space-y-4 rounded border p-5"><label className="block text-sm font-semibold">Request type<select name="requestType" className="mt-1 block w-full rounded border p-2"><option value="export">Export my data</option><option value="correction">Correct my data</option><option value="delete">Delete my account/data</option></select></label><label className="block text-sm font-semibold">Details<textarea name="note" maxLength={2000} rows={4} className="mt-1 block w-full rounded border p-2"/></label><p className="text-xs text-black/50">Invoices and statutory records may need to be retained. Deletion requests are reviewed rather than automatically hard-deleting those records.</p><button className="techpack-button">Submit request</button></form><section className="techpack-surface rounded border p-5"><h2 className="font-semibold">Your requests</h2><div className="mt-3 space-y-2">{requests?.length ? requests.map(request=><p key={request.id} className="flex justify-between text-sm"><span>{request.request_type}</span><span>{request.status}</span></p>) : <p className="text-sm text-black/45">No requests submitted.</p>}</div></section></div>;
}
